version: '3.9'

services:
  # База данных
  db:
    extends:
      file: database-services.yml
      service: db

  # Админка
  myadmin:
    extends:
      file: database-services.yml
      service: myadmin

  # Сервер
  server:
    hostname: server
    build:
      context: ..
      dockerfile: compose/images/Server
    restart: always
    volumes:
      - ./:/build
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - db
