version: '3.9'

services:
  # База данных
  db:
    image: mysql
    restart: always
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      MYSQL_DATABASE: main_database
    ports:
      - "3306:3306"

  # Админка
  myadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      PMA_HOST: db
    ports:
      - "8080:80"

  # Сервер
  server:
    hostname: server
    build:
      context: ..
      dockerfile: compose/images/Server
    restart: always
    volumes:
      - ./:/build
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - db
